config/routes.rb
Rails.application.routes.draw do
  #get '/bemvindo' => 'home#index'
  #get 'bemvindo', to: 'home#index'

  root 'home#index'

  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind, optional: true
  has_many :phones, dependent: :destroy
  has_one :address, dependent: :destroy

  accepts_nested_attributes_for :address #aceitar atributos aninhados de endereço (no mesmo formulário)
  #aceitar telefones
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, length: { minimum: 3}
  validates :email, presence: true

end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :contacts
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact, optional:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # antes de fazer essas ações (:show, etc) deve ser feito o :set_contact
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_listar_tipos_contatos, only: [:new, :edit, :update, :create]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(15)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    # Address.new para o formulário saber que tem um objeto endereço para preencher
    @contact.build_address
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # método para o select do formulário de contato com os tipos de contatos
    def set_listar_tipos_contatos
      @kind_options_for_select = Kind.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :kind_id, :rmk,
        address_attributes: [:street, :city, :state],
        phones_attributes: [:id, :phone, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to kinds_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to kinds_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
ESTADOS_BRASILEIROS = [
    ["Acre", "AC"],
    ["Alagoas", "AL"],
    ["Amapá", "AP"],
    ["Amazonas", "AM"],
    ["Bahia", "BA"],
    ["Ceará", "CE"],
    ["Distrito Federal", "DF"],
    ["Espírito Santo", "ES"],
    ["Goiás", "GO"],
    ["Maranhão", "MA"],
    ["Mato Grosso", "MT"],
    ["Mato Grosso do Sul", "MS"],
    ["Minas Gerais", "MG"],
    ["Pará", "PA"],
    ["Paraíba", "PB"],
    ["Paraná", "PR"],
    ["Pernambuco", "PE"],
    ["Piauí", "PI"],
    ["Rio de Janeiro", "RJ"],
    ["Rio Grande do Norte", "RN"],
    ["Rio Grande do Sul", "RS"],
    ["Rondônia", "RO"],
    ["Roraima", "RR"],
    ["Santa Catarina", "SC"],
    ["São Paulo", "SP"],
    ["Sergipe", "SE"],
    ["Tocantins", "TO"]
  ]

  def options_for_states(selected)
    options_for_select(ESTADOS_BRASILEIROS, selected)
  end


end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def teste_helper
    "Teste Helper"
  end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact, html: { class: "basic-grey"}) do |f| %>

<h1>Novo Contato</h1>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<div class="field">
  <%= f.label :kind_id %>
  <%= f.collection_select(:kind_id, @kind_options_for_select, :id, :description) %>
</div>

<!-- Endereço -->
<%= f.fields_for :address do |address_fields| %>
<div class="field">
  <%= address_fields.label :street %>
  <%= address_fields.text_field :street %>
</div>
<div class="field">
  <%= address_fields.label :city %>
  <%= address_fields.text_field :city %>
</div>
<div class="field">
  <%= address_fields.label :state %>
  <%= address_fields.select(:state, options_for_states(@contact.address.state)) %>
</div>
<% end %>

<!-- telefones -->
<div id="phones">
 <%= f.fields_for :phones do |phone_fields| %>
 <%= render partial: "phone_fields", locals: { f: phone_fields } %>
 <% end %>
 <div class="field">
   <%= f.label :phones, "<span class='glyphicon glyphicon-phone-alt' aria-hidden='true'></span>".html_safe %>
   <%= link_to_add_association('[Adicionar Telefone]', f, :phones) %>
 </div>
</div>

<div class="field">
  <%= f.label :rmk %>
  <%= f.text_area :rmk %>
</div>

<div class="actions">
  <%= f.submit("Enviar", class: "btn btn-primary") %>
  <%= link_to 'Back', contacts_path, class: "btn btn-success" %>
</div>

<% if contact.errors.any? %>
<div id="error_explanation">
  <h2><%= "#{pluralize(contact.errors.count, 'error')} #{t('messages.errors')} :" %></h2>

  <ul>
    <% contact.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<% end %>

app/views/contacts/_phone_fields.html.erb
  <div class="nested-fields">
    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone, class: "phone-field" %>
      <%= link_to_remove_association('[Remover]', f) %>
    </div>
  </div>

app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<div class="basic-grey">

  <script type="text/javascript">
    $.notify("<%= notice %>", "success")

  </script>

  <p id="notice"><%= notice %></p>

  <h1><%= "#{t('messages.listing')} #{@contacts.model.model_name.human(count: @contacts.count)}" %></h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= @contacts.model.human_attribute_name("name") %></th>
        <th><%= @contacts.model.human_attribute_name("kind") %></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.kind.description %></td>
        <td><%= link_to t('buttons.edit'), edit_contact_path(contact) %></td>
        <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%=  paginate @contacts %>
  <br>

  <%= link_to t('buttons.new'), new_contact_path, class: "btn btn-primary" %>
  <%= link_to t('buttons.home'), root_path, class: "btn btn-success" %>
</div>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @contact.kind %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<br/>
<div class="basic-grey">
  <h1>Seja Bem-Vindo!</h1>

  <ul>
  <li><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span> <%= link_to("Contatos", contacts_path)  %></li>
    <li><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> <%= link_to("Tipos", kinds_path) %></li>
  </ul>
</div>

app/views/kinds/_form.html.erb
<%= form_for(kind, html: { class: "basic-grey"}) do |f| %>
  <% if kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>New Kind</h1>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit("Enviar", class: "btn btn-primary") %>
    <%= link_to 'Back', kinds_path, class: "btn btn-success" %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<%= render 'form', kind: @kind %>

app/views/kinds/index.html.erb
<div class="basic-grey">
  <script type="text/javascript">
    $.notify("<%= notice %>", "success")

  </script>


  <h1>Listando os Tipos</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.description %></td>
        <td><%= link_to t('buttons.edit'), edit_kind_path(kind) %></td>
        <td><%= link_to t('buttons.destroy'), kind, method: :delete, data: { confirm: t('messages.confirm') } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo Tipo', new_kind_path, class: "btn btn-primary" %>
  <%= link_to('Voltar', root_path, class: "btn btn-success")%>
</div>

app/views/kinds/new.html.erb
<%= render 'form', kind: @kind %>

app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kind.description %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contatos</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>

</html>